THISPKG	= HUnit
SEARCH	= -package base
EXTRA_H_FLAGS =

SRCS	= \
	Test/HUnit.lhs  Test/HUnit/Base.lhs  Test/HUnit/Lang.lhs \
	Test/HUnit/Terminal.lhs  Test/HUnit/Text.lhs

# Here are the main rules.
include ../Makefile.common

# Here are any extra dependencies.

# C-files dependencies.

