name: HUnit
version: 1.6.2.0
synopsis: A unit testing framework for Haskell
category: Testing
stability: stable
author: Dean Herington
maintainer: Simon Hengel <sol@typeful.net>
license: BSD3
github: hspec/HUnit
description: |
  HUnit is a unit testing framework for Haskell, inspired by the
  JUnit tool for Java, see: <http://www.junit.org>.

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base == 4.*
  - deepseq
  - call-stack >= 0.3.0

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - Test.HUnit.Base
    - Test.HUnit.Lang
    - Test.HUnit.Terminal
    - Test.HUnit.Text
    - Test.HUnit

tests:
  tests:
    main: HUnitTests.hs
    source-dirs:
      - tests
      - examples
    dependencies:
      - filepath
      - HUnit
