name: MicroHs

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: sol/MicroHs@nightly
      - uses: actions/checkout@v4
      - run: mcabal -r build
